#!/bin/bash

# kill any running jobs on exit
cleanup() { kill $(jobs -p); }
trap cleanup EXIT

timeout=30

for url in $(cat $1); do
  ( timeout $timeout curl --silent "$url" 2>&1 >/dev/null && echo "$url" ) &
done

wait
