#!/bin/bash

# DEPENDENCIES:
# - curl (sudo apt-get install -y curl)
# - timeout (sudo apt-get install -y timeout)
for executable in curl timeout; do
  which $executable 2>&1 >/dev/null || (echo "Cannot find executable '$executable'" && exit 1)
done

# kill any running jobs on exit
cleanup() { kill $(jobs -p); }
trap cleanup EXIT

urls_file=${1:-./urls_file}
proxies_file=${2:-./proxies_file}
timeout=30

curl_with_proxy() {
  if [ -z "$DEBUG" ]; then
    timeout $timeout curl --silent --proxy "$2" "$1" 2>&1 >/dev/null
  else
    timeout $timeout curl --proxy "$2" "$1"
  fi
}

visit_auction() {
  url="$1"
  proxy="$(sort --random-sort "$proxies_file" | head -1)"

  echo " => $url via $proxy"
  curl_with_proxy "$url" "$proxy"

  if [ "$?" = "0" ]; then
    echo "    [ok] $url"
  else
    echo "    [fail] $url"
  fi
}

# sed is used to remove '?somevar=val' form end of url, because i dont know
# how to pass such a variable to curl without bash expanding the ? glob
# (i think this is the problem)
for url in $(sort --unique --random-sort $urls_file | sed 's|\?.*$||g'); do
  visit_auction "$url" &
done

echo
echo Waiting for responses...
echo

wait
